name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Runner
        run: |
          echo "Hello from my self-hosted runner"
          hostname
          whoami
          echo "Current directory:"
          pwd
          echo "Files:"
          dir
