name: Terraform Security Scan

on:
  workflow_dispatch:

jobs:
  tfsec:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Security Scan
        run: tfsec .
